-- AUTOGENERERT av scripts/generate-seed-sql.ts – ikke rediger for hånd.
-- Kjør `pnpm db:seed-sql` etter endringer i src/data/seed.ts.

insert into public.settings (id, national_average_kg, national_average_source, national_average_source_url, baseline_kg, baseline_label)
values (true, 13000, 'Miljødirektoratet: utslipp fra norsk forbruk (2020-tall, publisert 2024)', 'https://www.miljodirektoratet.no/aktuelt/fagmeldinger/2024/januar-2024/utslipp-av-klimagasser-fra-norsk-forbruk-er-beregnet/', 5600, 'Felles utslipp (offentlige tjenester, bygg og infrastruktur)')
on conflict (id) do nothing;

insert into public.categories (id, name, description, color, sort_order) values
  ('mat', 'Ukentlige matvaner', 'Hva du spiser i løpet av en vanlig uke.', '#728f3f', 1),
  ('transport', 'Reise og transport', 'Hverdagsreiser og ferier.', '#c46a2b', 2),
  ('bolig', 'Bolig og energi', 'Norsk strøm har svært lave utslipp, så boligen teller lite. Bygging og materialer ligger i felles utslipp.', '#3f6f8f', 3),
  ('forbruk', 'Forbruk og shopping', 'Ting du kjøper og tjenester du bruker.', '#8a5a9e', 4),
  ('avfall', 'Daglige rutiner (søppel)', 'Avfall og kildesortering.', '#8a7a5a', 5)
on conflict (id) do nothing;

insert into public.emission_methods (id, category_id, name, question, period, unit_label, kg_co2e_per_unit, choices, tip, source_name, source_url, sort_order) values
  ('rodt-kjott', 'mat', 'Rødt kjøtt', 'Hvor mange middager med storfe eller lam spiser du i uka?', 'week', 'middag', 5, '[{"label":"Aldri","value":0},{"label":"1 gang","value":1},{"label":"2 ganger","value":2},{"label":"3 ganger","value":3},{"label":"4 eller flere","value":5}]'::jsonb, 'Bytt én rødt kjøtt-middag i uka med kylling, fisk eller bønner – det sparer rundt 250 kg i året.', 'Our World in Data / Poore & Nemecek (2018): storfe 33,3 kg CO2e per kg', 'https://ourworldindata.org/environmental-impacts-of-food', 1),
  ('hvitt-kjott', 'mat', 'Kylling og svin', 'Hvor mange middager med kylling eller svin spiser du i uka?', 'week', 'middag', 1.7, '[{"label":"Aldri","value":0},{"label":"1–2 ganger","value":1.5},{"label":"3–4 ganger","value":3.5},{"label":"5 eller flere","value":6}]'::jsonb, null, 'Our World in Data / Poore & Nemecek (2018): svin 12,3 og kylling 9,9 kg CO2e per kg', 'https://ourworldindata.org/environmental-impacts-of-food', 2),
  ('fisk', 'mat', 'Fisk og sjømat', 'Hvor mange middager med fisk spiser du i uka?', 'week', 'middag', 2, '[{"label":"Aldri","value":0},{"label":"1 gang","value":1},{"label":"2 ganger","value":2},{"label":"3 eller flere","value":3.5}]'::jsonb, null, 'Our World in Data / Poore & Nemecek (2018): oppdrettsfisk 13,6 kg CO2e per kg', 'https://ourworldindata.org/environmental-impacts-of-food', 3),
  ('vegetar', 'mat', 'Vegetarmiddager', 'Hvor mange vegetar- eller veganmiddager spiser du i uka?', 'week', 'middag', 0.6, '[{"label":"Ingen","value":0},{"label":"1–2","value":1.5},{"label":"3–4","value":3.5},{"label":"5 eller flere","value":6}]'::jsonb, null, 'Our World in Data / Poore & Nemecek (2018): tofu 3,2 og grønnsaker ca. 0,5 kg CO2e per kg', 'https://ourworldindata.org/environmental-impacts-of-food', 4),
  ('meieri', 'mat', 'Meieriprodukter', 'Hvor mange porsjoner melk, ost eller yoghurt får du i deg i uka?', 'week', 'porsjon', 0.75, '[{"label":"Nesten ingen","value":1},{"label":"1 om dagen","value":7},{"label":"2 om dagen","value":14},{"label":"3 eller flere om dagen","value":24}]'::jsonb, 'Havre- og soyadrikk har rundt en tredjedel av utslippene til kumelk.', 'Our World in Data / Poore & Nemecek (2018): melk 3,15 og ost 23,9 kg CO2e per kg', 'https://ourworldindata.org/environmental-impacts-of-food', 5),
  ('fossilbil', 'transport', 'Bensin- eller dieselbil', 'Hvor mange kilometer kjører du med bensin- eller dieselbil i uka?', 'week', 'km', 0.19, '[{"label":"Ingen","value":0},{"label":"Litt (ca. 25 km)","value":25},{"label":"Til og fra jobb (ca. 150 km)","value":150},{"label":"Mye (ca. 400 km)","value":400}]'::jsonb, 'Samkjøring, kollektiv eller elbil på jobbreisen kutter mye.', 'SSB: ca. 150 g CO2 per kjørte km (bensin/diesel) + produksjon av bil', 'https://www.ssb.no/transport-og-reiseliv/artikler-og-publikasjoner/mindre-utslipp-per-kjorte-kilometer', 1),
  ('elbil', 'transport', 'Elbil', 'Hvor mange kilometer kjører du med elbil i uka?', 'week', 'km', 0.07, '[{"label":"Ingen","value":0},{"label":"Litt (ca. 25 km)","value":25},{"label":"Til og fra jobb (ca. 150 km)","value":150},{"label":"Mye (ca. 400 km)","value":400}]'::jsonb, null, 'NVE: norsk strøm 11,9 g CO2e/kWh (2024) + produksjon av bil og batteri', 'https://www.nve.no/energi/energisystem/energibruk/stroemdeklarasjoner/', 2),
  ('buss', 'transport', 'Buss', 'Hvor mange kilometer reiser du med buss i uka?', 'week', 'km', 0.059, '[{"label":"Ingen","value":0},{"label":"Litt (ca. 20 km)","value":20},{"label":"Til og fra jobb (ca. 100 km)","value":100},{"label":"Mye (ca. 300 km)","value":300}]'::jsonb, null, 'SSB: buss 59 g CO2 per passasjerkm (2019)', 'https://www.ssb.no/transport-og-reiseliv/artikler-og-publikasjoner/mindre-utslipp-fra-veitrafikk-fly-og-tog', 3),
  ('tog', 'transport', 'Tog, T-bane og trikk', 'Hvor mange kilometer reiser du med tog, T-bane eller trikk i uka?', 'week', 'km', 0.006, '[{"label":"Ingen","value":0},{"label":"Litt (ca. 20 km)","value":20},{"label":"Til og fra jobb (ca. 100 km)","value":100},{"label":"Mye (ca. 300 km)","value":300}]'::jsonb, null, 'SSB: jernbane 5,8 g CO2 per passasjerkm (2019)', 'https://www.ssb.no/transport-og-reiseliv/artikler-og-publikasjoner/mindre-utslipp-fra-veitrafikk-fly-og-tog', 4),
  ('sykkel-gange', 'transport', 'Sykkel og gange', 'Hvor mange kilometer sykler eller går du i uka?', 'week', 'km', 0, '[{"label":"Under 5 km","value":3},{"label":"5–20 km","value":12},{"label":"20–50 km","value":35},{"label":"Over 50 km","value":60}]'::jsonb, null, 'Regnes som utslippsfritt', null, 5),
  ('fly-innland', 'transport', 'Innenlandsfly', 'Hvor mange tur/retur-flyreiser innenlands tar du i året?', 'year', 'tur/retur', 180, '[{"label":"Ingen","value":0},{"label":"1–2","value":1.5},{"label":"3–5","value":4},{"label":"6 eller flere","value":8}]'::jsonb, 'Tog mellom de største byene har en brøkdel av utslippene til fly.', 'SSB: innenlands luftfart 181 g CO2 per passasjerkm (2019), ca. 1000 km tur/retur', 'https://www.ssb.no/transport-og-reiseliv/artikler-og-publikasjoner/mindre-utslipp-fra-veitrafikk-fly-og-tog', 6),
  ('fly-europa', 'transport', 'Flyreiser i Europa', 'Hvor mange tur/retur-flyreiser i Europa tar du i året?', 'year', 'tur/retur', 450, '[{"label":"Ingen","value":0},{"label":"1","value":1},{"label":"2–3","value":2.5},{"label":"4 eller flere","value":5}]'::jsonb, 'Én Europa-tur mindre i året sparer nesten et halvt tonn.', 'DEFRA 2024: kortdistanse 0,151 kg CO2e per passasjerkm, ca. 3000 km tur/retur', 'https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting', 7),
  ('fly-lang', 'transport', 'Langdistansefly', 'Hvor mange tur/retur-reiser utenfor Europa tar du i året?', 'year', 'tur/retur', 1750, '[{"label":"Ingen","value":0},{"label":"1","value":1},{"label":"2","value":2},{"label":"3 eller flere","value":3.5}]'::jsonb, 'Én langdistansereise gir mer utslipp enn et helt års middager.', 'DEFRA 2024: langdistanse 0,117 kg CO2e per passasjerkm, ca. 15 000 km tur/retur', 'https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting', 8),
  ('boligareal', 'bolig', 'Strøm i boligen', 'Hvor mange kvadratmeter bolig har du per person i husstanden?', 'year', 'm²', 1.6, '[{"label":"Under 25 m²","value":20},{"label":"25–40 m²","value":32},{"label":"40–60 m²","value":50},{"label":"Over 60 m²","value":75}]'::jsonb, null, 'NVE: 11,9 g CO2e per kWh (2024), ca. 135 kWh per m² per år', 'https://www.nve.no/energi/energisystem/energibruk/stroemdeklarasjoner/', 1),
  ('oppvarming', 'bolig', 'Oppvarming', 'Hvordan varmes boligen din hovedsakelig opp?', 'year', 'kg CO2e', 1, '[{"label":"Strøm (varmepumpe, panelovner, gulvvarme)","value":0},{"label":"Fjernvarme","value":100},{"label":"Vedfyring","value":75},{"label":"Gass eller parafin","value":1250}]'::jsonb, 'Bytt ut gass eller parafin med varmepumpe – Enova gir støtte.', 'Anslag: ca. 5000 kWh varme per person; gass ca. 0,25 kg CO2e/kWh', null, 2),
  ('klaer', 'forbruk', 'Nye klær', 'Hvor mange nye klesplagg kjøper du i måneden?', 'month', 'plagg', 10, '[{"label":"Ingen / bruktkjøp","value":0},{"label":"1","value":1},{"label":"2–4","value":3},{"label":"5 eller flere","value":6}]'::jsonb, 'Bruktkjøp og reparasjon gir nesten null ekstra utslipp.', 'CONCITO: t-skjorte ca. 7, jeans 11–20 kg CO2e per plagg', 'https://concito.dk/klimapakker/forbrug/toejets-klimaaftryk', 1),
  ('elektronikk', 'forbruk', 'Elektronikk', 'Hvor mange nye mobiler, PC-er eller nettbrett kjøper du i året?', 'year', 'enhet', 150, '[{"label":"Ingen","value":0},{"label":"1","value":1},{"label":"2","value":2},{"label":"3 eller flere","value":4}]'::jsonb, 'Å bruke mobilen ett år ekstra er et av de enkleste kuttene.', 'Produksjon: mobil 80–110 kg, bærbar PC 200–350 kg CO2e (produsenters livsløpsanalyser)', null, 2),
  ('storre-innkjop', 'forbruk', 'Møbler og hvitevarer', 'Hvor mange større innkjøp (møbler, hvitevarer) gjør du i året?', 'year', 'innkjøp', 200, '[{"label":"Ingen","value":0},{"label":"1","value":1},{"label":"2–3","value":2.5},{"label":"4 eller flere","value":5}]'::jsonb, null, 'Anslag fra livsløpsanalyser (sofa ca. 100–200, kjøleskap ca. 200–400 kg CO2e)', null, 3),
  ('tjenester', 'forbruk', 'Fritid, restaurant og tjenester', 'Hvor mye bruker du på fritid, restaurantbesøk og tjenester i måneden?', 'month', 'kr', 0.015, '[{"label":"Under 1 000 kr","value":500},{"label":"1 000–3 000 kr","value":2000},{"label":"3 000–6 000 kr","value":4500},{"label":"Over 6 000 kr","value":8000}]'::jsonb, null, 'Utledet fra Miljødirektoratet: husholdningers utslipp per forbrukskrone', 'https://www.miljodirektoratet.no/aktuelt/fagmeldinger/2024/januar-2024/utslipp-av-klimagasser-fra-norsk-forbruk-er-beregnet/', 4),
  ('restavfall', 'avfall', 'Restavfall', 'Hvor mange ganger i uka tar du ut en full pose restavfall?', 'week', 'pose', 2, '[{"label":"1 gang","value":1},{"label":"2 ganger","value":2},{"label":"3–4 ganger","value":3.5},{"label":"5 eller flere","value":6}]'::jsonb, null, 'Miljødirektoratet (avfallsforbrenning): ca. 0,5 kg CO2 per kg restavfall, ca. 4 kg per pose', 'https://www.miljodirektoratet.no/ansvarsomrader/klima/klimakvoter/avfallsforbrenningsanlegg/', 1),
  ('kildesortering', 'avfall', 'Kildesortering', 'Kildesorterer du plast, papir, glass og matavfall?', 'year', 'kg CO2e', 1, '[{"label":"Ja, alt","value":0},{"label":"Delvis","value":35},{"label":"Nei","value":70}]'::jsonb, 'Kildesortering er gratis og tar et par minutter om dagen.', 'Anslag: ca. 25 kg plast per person, ca. 2,7 kg CO2 per kg plast som brennes', null, 2)
on conflict (id) do nothing;
