-- AUTOGENERERT av scripts/generate-seed-sql.ts – ikke rediger for hånd.
-- Kjør `pnpm db:seed-sql` etter endringer i src/data/seed.ts.

insert into public.settings (id, national_average_kg, national_average_source, national_average_source_url, baseline_kg, baseline_label, target_kg, target_label)
values (true, 7800, 'Hot or Cool Institute (2025): livsstilsfotavtrykk for en gjennomsnittlig nordmann', 'https://hotorcool.org/wp-content/uploads/2025/10/A_Climate_for_Sufficiency_report_FULL_REPORT-1.pdf', 500, 'Tjenester alle bruker (helse, utdanning, kommunikasjon)', 1100, '1,5-gradersmålet 2035')
on conflict (id) do nothing;

insert into public.categories (id, name, description, color, sort_order) values
  ('mat', 'Ukentlige matvaner', 'Hva du spiser i løpet av en vanlig uke.', '#728f3f', 1),
  ('transport', 'Reise og transport', 'Hverdagsreiser og ferier.', '#c46a2b', 2),
  ('bolig', 'Bolig og energi', 'Norsk strøm har lave utslipp, så det er mest bygging og vedlikehold av boligen som teller.', '#3f6f8f', 3),
  ('forbruk', 'Forbruk og fritid', 'Ting du kjøper og hva du gjør på fritiden.', '#8a5a9e', 4),
  ('avfall', 'Daglige rutiner (søppel)', 'Avfall og kildesortering.', '#8a7a5a', 5)
on conflict (id) do nothing;

insert into public.emission_methods (id, category_id, name, question, period, unit_label, kg_co2e_per_unit, choices, tip, source_name, source_url, sort_order, easy_win_text, easy_win_units, easy_win_replacement_id) values
  ('rodt-kjott', 'mat', 'Rødt kjøtt', 'Hvor mange middager med storfe eller lam spiser du i uka?', 'week', 'middag', 5, '[{"label":"Aldri","value":0},{"label":"1 gang","value":1},{"label":"2 ganger","value":2},{"label":"3 ganger","value":3},{"label":"4 eller flere","value":5}]'::jsonb, 'Bytt én rødt kjøtt-middag i uka med kylling, fisk eller bønner – det sparer rundt 250 kg i året.', 'Poore & Nemecek (2018) via Our World in Data: storfe 33,3 kg CO2e per kg', 'https://ourworldindata.org/grapher/ghg-per-kg-poore', 1, 'bytter ut én middag med rødt kjøtt i uka med en vegetarmiddag', 1, 'vegetar'),
  ('hvitt-kjott', 'mat', 'Kylling og svin', 'Hvor mange middager med kylling eller svin spiser du i uka?', 'week', 'middag', 1.7, '[{"label":"Aldri","value":0},{"label":"1–2 ganger","value":1.5},{"label":"3–4 ganger","value":3.5},{"label":"5 eller flere","value":6}]'::jsonb, null, 'Poore & Nemecek (2018) via Our World in Data: svin 12,3 og kylling 9,9 kg CO2e per kg', 'https://ourworldindata.org/grapher/ghg-per-kg-poore', 2, 'bytter ut én kylling- eller svinemiddag i uka med en vegetarmiddag', 1, 'vegetar'),
  ('fisk', 'mat', 'Fisk og sjømat', 'Hvor mange middager med fisk spiser du i uka?', 'week', 'middag', 2, '[{"label":"Aldri","value":0},{"label":"1 gang","value":1},{"label":"2 ganger","value":2},{"label":"3 eller flere","value":3.5}]'::jsonb, null, 'Poore & Nemecek (2018) via Our World in Data: oppdrettsfisk 13,6 kg CO2e per kg', 'https://ourworldindata.org/grapher/ghg-per-kg-poore', 3, null, null, null),
  ('vegetar', 'mat', 'Vegetarmiddager', 'Hvor mange vegetar- eller veganmiddager spiser du i uka?', 'week', 'middag', 0.6, '[{"label":"Ingen","value":0},{"label":"1–2","value":1.5},{"label":"3–4","value":3.5},{"label":"5 eller flere","value":6}]'::jsonb, null, 'Poore & Nemecek (2018) via Our World in Data: tofu 3,2 og grønnsaker ca. 0,5 kg CO2e per kg', 'https://ourworldindata.org/grapher/ghg-per-kg-poore', 4, null, null, null),
  ('meieri', 'mat', 'Meieriprodukter', 'Hvor mange porsjoner melk, ost eller yoghurt får du i deg i uka?', 'week', 'porsjon', 0.75, '[{"label":"Nesten ingen","value":1},{"label":"1 om dagen","value":7},{"label":"2 om dagen","value":14},{"label":"3 eller flere om dagen","value":24}]'::jsonb, 'Havre- og soyadrikk har rundt en tredjedel av utslippene til kumelk.', 'Poore & Nemecek (2018) via Our World in Data: melk 3,15 og ost 23,9 kg CO2e per kg', 'https://ourworldindata.org/grapher/ghg-per-kg-poore', 5, 'dropper én porsjon melk, ost eller yoghurt om dagen', 7, null),
  ('ovrig-mat', 'mat', 'Frokost, lunsj og snacks', 'Hvordan er resten av kostholdet ditt (frokost, lunsj, mellommåltider, drikke)?', 'year', 'kg CO2e', 1, '[{"label":"Mest plantebasert","value":450},{"label":"Som folk flest","value":800},{"label":"Mye kjøttpålegg, ost, kaffe og snacks","value":1200}]'::jsonb, null, 'Hot or Cool Institute (2025): nordmenns kosthold 2,1 t CO2e per år, fratrukket middager og meieri', 'https://hotorcool.org/wp-content/uploads/2025/10/A_Climate_for_Sufficiency_report_FULL_REPORT-1.pdf', 6, null, null, null),
  ('fossilbil', 'transport', 'Bensin- eller dieselbil', 'Hvor mange kilometer kjører du med bensin- eller dieselbil i uka?', 'week', 'km', 0.235, '[{"label":"Ingen","value":0},{"label":"Litt (ca. 25 km)","value":25},{"label":"Til og fra jobb (ca. 150 km)","value":150},{"label":"Mye (ca. 400 km)","value":400}]'::jsonb, 'Samkjøring, kollektiv eller elbil på jobbreisen kutter mye.', 'ICCT (2025): bensinbil 235 g CO2e per km, hele livsløpet', 'https://theicct.org/publication/electric-cars-life-cycle-analysis-emissions-europe-jul25/', 1, 'tar én kjøretur mindre til jobb i uka (ca. 30 km tur/retur) og sykler, går eller jobber hjemmefra i stedet', 30, 'sykkel-gange'),
  ('elbil', 'transport', 'Elbil', 'Hvor mange kilometer kjører du med elbil i uka?', 'week', 'km', 0.052, '[{"label":"Ingen","value":0},{"label":"Litt (ca. 25 km)","value":25},{"label":"Til og fra jobb (ca. 150 km)","value":150},{"label":"Mye (ca. 400 km)","value":400}]'::jsonb, null, 'ICCT (2025): elbil på fornybar strøm 52 g CO2e per km, hele livsløpet', 'https://theicct.org/publication/electric-cars-life-cycle-analysis-emissions-europe-jul25/', 2, null, null, null),
  ('buss', 'transport', 'Buss', 'Hvor mange kilometer reiser du med buss i uka?', 'week', 'km', 0.059, '[{"label":"Ingen","value":0},{"label":"Litt (ca. 20 km)","value":20},{"label":"Til og fra jobb (ca. 100 km)","value":100},{"label":"Mye (ca. 300 km)","value":300}]'::jsonb, null, 'SSB: buss 59 g CO2 per passasjerkm (2019)', 'https://www.ssb.no/transport-og-reiseliv/artikler-og-publikasjoner/mindre-utslipp-fra-veitrafikk-fly-og-tog', 3, null, null, null),
  ('tog', 'transport', 'Tog, T-bane og trikk', 'Hvor mange kilometer reiser du med tog, T-bane eller trikk i uka?', 'week', 'km', 0.006, '[{"label":"Ingen","value":0},{"label":"Litt (ca. 20 km)","value":20},{"label":"Til og fra jobb (ca. 100 km)","value":100},{"label":"Mye (ca. 300 km)","value":300}]'::jsonb, null, 'SSB: jernbane 5,8 g CO2 per passasjerkm (2019)', 'https://www.ssb.no/transport-og-reiseliv/artikler-og-publikasjoner/mindre-utslipp-fra-veitrafikk-fly-og-tog', 4, null, null, null),
  ('sykkel-gange', 'transport', 'Sykkel og gange', 'Hvor mange kilometer sykler eller går du i uka?', 'week', 'km', 0, '[{"label":"Under 5 km","value":3},{"label":"5–20 km","value":12},{"label":"20–50 km","value":35},{"label":"Over 50 km","value":60}]'::jsonb, null, 'Regnes som utslippsfritt', null, 5, null, null, null),
  ('fly-innland', 'transport', 'Innenlandsfly', 'Hvor mange tur/retur-flyreiser innenlands tar du i året?', 'year', 'tur/retur', 180, '[{"label":"Ingen","value":0},{"label":"1–2","value":1.5},{"label":"3–5","value":4},{"label":"6 eller flere","value":8}]'::jsonb, 'Tog mellom de største byene har en brøkdel av utslippene til fly.', 'SSB: innenlands luftfart 181 g CO2 per passasjerkm (2019), ca. 1000 km tur/retur', 'https://www.ssb.no/transport-og-reiseliv/artikler-og-publikasjoner/mindre-utslipp-fra-veitrafikk-fly-og-tog', 6, 'tar toget i stedet for fly på én innenlandsreise i året', 1, null),
  ('fly-europa', 'transport', 'Flyreiser i Europa', 'Hvor mange tur/retur-flyreiser i Europa tar du i året?', 'year', 'tur/retur', 450, '[{"label":"Ingen","value":0},{"label":"1","value":1},{"label":"2–3","value":2.5},{"label":"4 eller flere","value":5}]'::jsonb, 'Én Europa-tur mindre i året sparer nesten et halvt tonn.', 'DEFRA 2024: kortdistanse 0,151 kg CO2e per passasjerkm, ca. 3000 km tur/retur', 'https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting', 7, null, null, null),
  ('fly-lang', 'transport', 'Langdistansefly', 'Hvor mange tur/retur-reiser utenfor Europa tar du i året?', 'year', 'tur/retur', 1750, '[{"label":"Ingen","value":0},{"label":"1","value":1},{"label":"2","value":2},{"label":"3 eller flere","value":3.5}]'::jsonb, 'Én langdistansereise gir mer utslipp enn et helt års middager.', 'DEFRA 2024: langdistanse 0,117 kg CO2e per passasjerkm, ca. 15 000 km tur/retur', 'https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting', 8, null, null, null),
  ('boligareal', 'bolig', 'Boligareal', 'Hvor mange kvadratmeter bolig har du per person i husstanden?', 'year', 'm²', 12.6, '[{"label":"Under 25 m²","value":20},{"label":"25–40 m²","value":32},{"label":"40–60 m²","value":50},{"label":"Over 60 m²","value":75}]'::jsonb, 'Å dele bolig med flere er et av de mest effektive klimatiltakene – utslippene fordeles.', 'Hot or Cool Institute (2025): boligareal 0,6 t per nordmann; NVE: strøm 11,9 g CO2e/kWh', 'https://hotorcool.org/wp-content/uploads/2025/10/A_Climate_for_Sufficiency_report_FULL_REPORT-1.pdf', 1, null, null, null),
  ('oppvarming', 'bolig', 'Oppvarming', 'Hvordan varmes boligen din hovedsakelig opp?', 'year', 'kg CO2e', 1, '[{"label":"Strøm (varmepumpe, panelovner, gulvvarme)","value":0},{"label":"Fjernvarme","value":100},{"label":"Vedfyring","value":75},{"label":"Gass","value":1150}]'::jsonb, 'Bytt ut gassfyring med varmepumpe – Enova gir støtte.', 'Hafslund: fjernvarme 20,8 g CO2e/kWh (2025); DEFRA: propan ca. 0,23 kg/kWh; ca. 5000 kWh varme per person', 'https://www.hafslund.no/no/produkter-og-tjenester/fjernvarme/nokkeltall-for-avfallsforbrenning-og-fjernvarmeproduksjon', 2, null, null, null),
  ('klaer', 'forbruk', 'Nye klær', 'Hvor mange nye klesplagg kjøper du i måneden?', 'month', 'plagg', 10, '[{"label":"Ingen / bruktkjøp","value":0},{"label":"1","value":1},{"label":"2–4","value":3},{"label":"5 eller flere","value":6}]'::jsonb, 'Bruktkjøp og reparasjon gir nesten null ekstra utslipp.', 'CONCITO: t-skjorte ca. 7, jeans 11–20 kg CO2e per plagg', 'https://concito.dk/klimapakker/forbrug/toejets-klimaaftryk', 1, 'kjøper ett nytt klesplagg mindre i måneden', 1, null),
  ('mobil', 'forbruk', 'Ny mobil eller nettbrett', 'Hvor mange nye mobiler eller nettbrett kjøper du i året?', 'year', 'enhet', 56, '[{"label":"Ingen","value":0},{"label":"Én hvert 3. år","value":0.33},{"label":"Én i året","value":1},{"label":"2 eller flere","value":2.5}]'::jsonb, 'Å bruke mobilen ett år ekstra er et av de enkleste kuttene.', 'Apple Product Environmental Report: iPhone 16 (128 GB) 56 kg CO2e', 'https://www.apple.com/environment/pdf/products/iphone/iPhone_16_and_iPhone_16_Plus_PER_Sept2024.pdf', 2, 'bruker mobilen ett år lenger før du bytter', 0.5, null),
  ('pc', 'forbruk', 'Ny PC', 'Hvor ofte kjøper du ny PC?', 'year', 'PC', 158, '[{"label":"Sjeldnere enn hvert 5. år","value":0.15},{"label":"Hvert 3.–4. år","value":0.3},{"label":"Annethvert år","value":0.5},{"label":"Hvert år","value":1}]'::jsonb, null, 'Apple Product Environmental Report: MacBook Air M3 158 kg CO2e', 'https://www.apple.com/environment/pdf/products/notebooks/M3_MacBook_Air_PER_March2024.pdf', 3, null, null, null),
  ('fritid', 'forbruk', 'Fritid, restaurant og hotell', 'Hvor mye bruker du på restaurant, hotell, hobbyer og opplevelser, sammenlignet med folk flest?', 'year', 'kg CO2e', 1, '[{"label":"Mye mindre","value":400},{"label":"Omtrent som folk flest","value":1000},{"label":"Mer","value":1500},{"label":"Mye mer","value":2200}]'::jsonb, null, 'Hot or Cool Institute (2025): fritid 1,0 t CO2e per nordmann per år', 'https://hotorcool.org/wp-content/uploads/2025/10/A_Climate_for_Sufficiency_report_FULL_REPORT-1.pdf', 4, null, null, null),
  ('restavfall', 'avfall', 'Restavfall', 'Hvor mange ganger i uka tar du ut en full pose restavfall?', 'week', 'pose', 2, '[{"label":"1 gang","value":1},{"label":"2 ganger","value":2},{"label":"3–4 ganger","value":3.5},{"label":"5 eller flere","value":6}]'::jsonb, null, 'Hafslund (Klemetsrud/Haraldrud 2025): 0,51 t fossil CO2 per tonn avfall; ca. 4 kg per pose', 'https://www.hafslund.no/no/produkter-og-tjenester/fjernvarme/nokkeltall-for-avfallsforbrenning-og-fjernvarmeproduksjon', 1, 'sorterer ut nok matavfall og plast til én pose restavfall mindre i uka', 1, null),
  ('kildesortering', 'avfall', 'Kildesortering', 'Kildesorterer du plast, papir, glass og matavfall?', 'year', 'kg CO2e', 1, '[{"label":"Ja, alt","value":0},{"label":"Delvis","value":25},{"label":"Nei","value":50}]'::jsonb, 'Kildesortering er gratis og tar et par minutter om dagen.', 'Grønt Punkt: ca. 18 kg plastemballasje per person i året; ca. 2,7 kg CO2 per kg plast som brennes', 'https://www.grontpunkt.no/aktuelt/nyheter/samler-inn-for-lite-plastemballasje', 2, 'begynner å sortere plast, papir, glass og matavfall', 50, null)
on conflict (id) do nothing;
